[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r ../requirements.txt"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "dumpstr-backend"
type = "web"

[services.dumpstr-backend]
port = 8000
internalPort = 8000

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"